import { getTranslations } from "next-intl/server";

import { PricingPage } from "./_components/pricing-page";

export default async function PricingPageServer() {
  const t = await getTranslations("pricing");

  const translations = {
    back: t("back"),
    title: t("title"),
    subtitle: t("subtitle"),
    billingTitle: t("billing.title"),
    billingDescription: t("billing.description"),
    billingExample: t("billing.example"),
    planTiers: t("planTiers"),
    free: {
      name: t("free.name"),
      price: t("free.price"),
      period: t("free.period"),
      features: [t("free.f1"), t("free.f2"), t("free.f3"), t("free.f4"), t("free.f5"), t("free.f6"), t("free.f7")],
      note: t("free.note"),
    },
    pro: {
      name: t("pro.name"),
      from: t("pro.from"),
      price: t("pro.price"),
      period: t("pro.period"),
      features: [
        { text: t("pro.f1"), sub: t("pro.f1sub") },
        { text: t("pro.f2"), sub: t("pro.f2sub") },
        { text: t("pro.f3"), sub: t("pro.f3sub") },
        { text: t("pro.f4"), sub: t("pro.f4sub") },
        { text: t("pro.f5"), sub: t("pro.f5sub") },
        { text: t("pro.f6") },
        { text: t("pro.f7") },
        { text: t("pro.f8") },
        { text: t("pro.f9"), sub: t("pro.f9sub") },
      ],
    },
    team: {
      name: t("team.name"),
      from: t("team.from"),
      price: t("team.price"),
      period: t("team.period"),
      features: [t("team.f1"), t("team.f2"), t("team.f3"), t("team.f4"), t("team.f5"), t("team.f6"), t("team.f7")],
    },
    enterprise: {
      name: t("enterprise.name"),
      price: t("enterprise.price"),
      features: [
        t("enterprise.f1"),
        t("enterprise.f2"),
        t("enterprise.f3"),
        t("enterprise.f4"),
        t("enterprise.f5"),
        t("enterprise.f6"),
      ],
    },
    computeTitle: t("compute.title"),
    computeDescription: t("compute.description"),
    computeTable: {
      headers: [
        t("compute.headers.size"),
        t("compute.headers.price"),
        t("compute.headers.cpu"),
        t("compute.headers.dedicated"),
        t("compute.headers.ram"),
        t("compute.headers.directConnections"),
        t("compute.headers.poolerConnections"),
      ],
      rows: [
        [
          t("compute.rows.micro.size"),
          t("compute.rows.micro.price"),
          t("compute.rows.micro.cpu"),
          t("compute.rows.micro.dedicated"),
          t("compute.rows.micro.ram"),
          t("compute.rows.micro.direct"),
          t("compute.rows.micro.pooler"),
        ],
        [
          t("compute.rows.small.size"),
          t("compute.rows.small.price"),
          t("compute.rows.small.cpu"),
          t("compute.rows.small.dedicated"),
          t("compute.rows.small.ram"),
          t("compute.rows.small.direct"),
          t("compute.rows.small.pooler"),
        ],
        [
          t("compute.rows.medium.size"),
          t("compute.rows.medium.price"),
          t("compute.rows.medium.cpu"),
          t("compute.rows.medium.dedicated"),
          t("compute.rows.medium.ram"),
          t("compute.rows.medium.direct"),
          t("compute.rows.medium.pooler"),
        ],
        [
          t("compute.rows.large.size"),
          t("compute.rows.large.price"),
          t("compute.rows.large.cpu"),
          t("compute.rows.large.dedicated"),
          t("compute.rows.large.ram"),
          t("compute.rows.large.direct"),
          t("compute.rows.large.pooler"),
        ],
        [
          t("compute.rows.xl.size"),
          t("compute.rows.xl.price"),
          t("compute.rows.xl.cpu"),
          t("compute.rows.xl.dedicated"),
          t("compute.rows.xl.ram"),
          t("compute.rows.xl.direct"),
          t("compute.rows.xl.pooler"),
        ],
        [
          t("compute.rows.2xl.size"),
          t("compute.rows.2xl.price"),
          t("compute.rows.2xl.cpu"),
          t("compute.rows.2xl.dedicated"),
          t("compute.rows.2xl.ram"),
          t("compute.rows.2xl.direct"),
          t("compute.rows.2xl.pooler"),
        ],
        [
          t("compute.rows.4xl.size"),
          t("compute.rows.4xl.price"),
          t("compute.rows.4xl.cpu"),
          t("compute.rows.4xl.dedicated"),
          t("compute.rows.4xl.ram"),
          t("compute.rows.4xl.direct"),
          t("compute.rows.4xl.pooler"),
        ],
        [
          t("compute.rows.8xl.size"),
          t("compute.rows.8xl.price"),
          t("compute.rows.8xl.cpu"),
          t("compute.rows.8xl.dedicated"),
          t("compute.rows.8xl.ram"),
          t("compute.rows.8xl.direct"),
          t("compute.rows.8xl.pooler"),
        ],
        [
          t("compute.rows.12xl.size"),
          t("compute.rows.12xl.price"),
          t("compute.rows.12xl.cpu"),
          t("compute.rows.12xl.dedicated"),
          t("compute.rows.12xl.ram"),
          t("compute.rows.12xl.direct"),
          t("compute.rows.12xl.pooler"),
        ],
        [
          t("compute.rows.16xl.size"),
          t("compute.rows.16xl.price"),
          t("compute.rows.16xl.cpu"),
          t("compute.rows.16xl.dedicated"),
          t("compute.rows.16xl.ram"),
          t("compute.rows.16xl.direct"),
          t("compute.rows.16xl.pooler"),
        ],
        [
          t("compute.rows.over16xl.size"),
          t("compute.rows.over16xl.price"),
          t("compute.rows.over16xl.cpu"),
          t("compute.rows.over16xl.dedicated"),
          t("compute.rows.over16xl.ram"),
          t("compute.rows.over16xl.direct"),
          t("compute.rows.over16xl.pooler"),
        ],
      ],
    },
    computeNote: t("compute.note"),
    diskTitle: t("disk.title"),
    generalPurpose: t("disk.generalPurpose"),
    highPerformance: t("disk.highPerformance"),
    diskFeatures: [t("disk.f1"), t("disk.f2"), t("disk.f3"), t("disk.f4"), t("disk.f5"), t("disk.f6")],
    addonsTitle: t("addons.title"),
    addonsTable: {
      headers: [t("addons.headers.addon"), t("addons.headers.price")],
      rows: [
        [t("addons.rows.pitr.name"), t("addons.rows.pitr.price")],
        [t("addons.rows.domain.name"), t("addons.rows.domain.price")],
        [t("addons.rows.branching.name"), t("addons.rows.branching.price")],
        [t("addons.rows.mfa.name"), t("addons.rows.mfa.price")],
        [t("addons.rows.saml.name"), t("addons.rows.saml.price")],
        [t("addons.rows.logdrains.name"), t("addons.rows.logdrains.price")],
        [t("addons.rows.images.name"), t("addons.rows.images.price")],
      ],
    },
    featureComparison: t("featureComparison"),
    featureCategories: [
      {
        title: t("database"),
        rows: [
          {
            feature: "Dedicated Postgres Database",
            free: "Included",
            pro: "Included",
            team: "Included",
            enterprise: "Included",
          },
          {
            feature: "Unlimited API requests",
            free: "Included",
            pro: "Included",
            team: "Included",
            enterprise: "Included",
          },
          {
            feature: "Database size",
            free: "500 MB per project",
            pro: "8 GB per project, then $0.125/GB",
            team: "8 GB per project, then $0.125/GB",
            enterprise: "Custom",
          },
          {
            feature: "Advanced disk config",
            free: "Not included",
            pro: "Included",
            team: "Included",
            enterprise: "Included",
          },
          { feature: "Automatic backups", free: "Not included", pro: "7 days", team: "14 days", enterprise: "Custom" },
          {
            feature: "Point in time recovery",
            free: "Not included",
            pro: "$100/mo per 7 days",
            team: "$100/mo per 7 days",
            enterprise: "$100/mo, >28 days available",
          },
          { feature: "Pausing", free: "After 1 week", pro: "Never", team: "Never", enterprise: "Never" },
          {
            feature: "Branching",
            free: "Not included",
            pro: "$0.01344/branch/hour",
            team: "$0.01344/branch/hour",
            enterprise: "Custom",
          },
          {
            feature: "Egress",
            free: "5 GB included",
            pro: "250 GB, then $0.09/GB",
            team: "250 GB, then $0.09/GB",
            enterprise: "Custom",
          },
          {
            feature: "Pipelines",
            free: "Not included",
            pro: "$0.053/pipeline/hour",
            team: "$0.053/pipeline/hour",
            enterprise: "Custom",
          },
        ],
      },
      {
        title: t("auth"),
        rows: [
          { feature: "Total Users", free: "Unlimited", pro: "Unlimited", team: "Unlimited", enterprise: "Unlimited" },
          {
            feature: "MAUs",
            free: "50,000 included",
            pro: "100,000, then $0.00325/MAU",
            team: "100,000, then $0.00325/MAU",
            enterprise: "Custom",
          },
          {
            feature: "User data ownership",
            free: "Included",
            pro: "Included",
            team: "Included",
            enterprise: "Included",
          },
          {
            feature: "Anonymous Sign-ins",
            free: "Included",
            pro: "Included",
            team: "Included",
            enterprise: "Included",
          },
          {
            feature: "Social OAuth providers",
            free: "Included",
            pro: "Included",
            team: "Included",
            enterprise: "Included",
          },
          {
            feature: "Custom SMTP server",
            free: "Included",
            pro: "Included",
            team: "Included",
            enterprise: "Included",
          },
          {
            feature: "Remove branding from emails",
            free: "Not included",
            pro: "Included",
            team: "Included",
            enterprise: "Included",
          },
          { feature: "Auth Audit Logs", free: "1 hour", pro: "7 days", team: "28 days", enterprise: "Included" },
          {
            feature: "Basic Multi-Factor Auth",
            free: "Included",
            pro: "Included",
            team: "Included",
            enterprise: "Included",
          },
          {
            feature: "Advanced MFA - Phone",
            free: "Not included",
            pro: "$75/mo first, $10/mo each",
            team: "$75/mo first, $10/mo each",
            enterprise: "Custom",
          },
          {
            feature: "Third-Party MAUs",
            free: "50,000 included",
            pro: "100,000, then $0.00325/MAU",
            team: "100,000, then $0.00325/MAU",
            enterprise: "Custom",
          },
          {
            feature: "Single Sign-On (SAML 2.0)",
            free: "Not included",
            pro: "50, then $0.015/MAU",
            team: "50, then $0.015/MAU",
            enterprise: "Contact Us",
          },
          {
            feature: "Leaked password protection",
            free: "Not included",
            pro: "Included",
            team: "Included",
            enterprise: "Included",
          },
          {
            feature: "Single session per user",
            free: "Not included",
            pro: "Included",
            team: "Included",
            enterprise: "Included",
          },
          {
            feature: "Session timeouts",
            free: "Not included",
            pro: "Included",
            team: "Included",
            enterprise: "Included",
          },
          {
            feature: "Auth Hooks",
            free: "JWT, custom email/SMS",
            pro: "JWT, custom email/SMS",
            team: "All",
            enterprise: "All",
          },
          {
            feature: "Advanced security features",
            free: "Not included",
            pro: "Not included",
            team: "Not included",
            enterprise: "Contact Us",
          },
        ],
      },
      {
        title: t("storage"),
        rows: [
          {
            feature: "Storage",
            free: "1 GB included",
            pro: "100 GB, then $0.0213/GB",
            team: "100 GB, then $0.0213/GB",
            enterprise: "Custom",
          },
          {
            feature: "Cached Egress",
            free: "5 GB included",
            pro: "250 GB, then $0.03/GB",
            team: "250 GB, then $0.03/GB",
            enterprise: "Custom",
          },
          {
            feature: "Custom access controls",
            free: "Included",
            pro: "Included",
            team: "Included",
            enterprise: "Included",
          },
          { feature: "Max file upload size", free: "50 MB", pro: "500 GB", team: "500 GB", enterprise: "Custom" },
          {
            feature: "Content Delivery Network",
            free: "Basic CDN",
            pro: "Smart CDN",
            team: "Smart CDN",
            enterprise: "Smart CDN",
          },
          {
            feature: "Image Transformations",
            free: "Not included",
            pro: "100 origin, then $5/1000",
            team: "100 origin, then $5/1000",
            enterprise: "Custom",
          },
        ],
      },
      {
        title: t("edgeFunctions"),
        rows: [
          {
            feature: "Invocations",
            free: "500,000 included",
            pro: "2M, then $2/1M",
            team: "2M, then $2/1M",
            enterprise: "Custom",
          },
        ],
      },
      {
        title: t("realtime"),
        rows: [
          { feature: "Postgres Changes", free: "Included", pro: "Included", team: "Included", enterprise: "Included" },
          {
            feature: "Concurrent Peak Connections",
            free: "200 included",
            pro: "500, then $10/1000",
            team: "500, then $10/1000",
            enterprise: "Custom",
          },
          {
            feature: "Messages Per Month",
            free: "2M included",
            pro: "5M, then $2.50/M",
            team: "5M, then $2.50/M",
            enterprise: "Volume discounts",
          },
          { feature: "Max Message Size", free: "256 KB", pro: "3 MB", team: "3 MB", enterprise: "Custom" },
        ],
      },
      {
        title: t("dashboard"),
        rows: [
          { feature: "Team members", free: "Unlimited", pro: "Unlimited", team: "Unlimited", enterprise: "Unlimited" },
        ],
      },
      {
        title: t("security"),
        rows: [
          { feature: "Log retention (API & DB)", free: "1 day", pro: "7 days", team: "28 days", enterprise: "90 days" },
          {
            feature: "Log Drain",
            free: "Not included",
            pro: "$60/drain/mo",
            team: "$60/drain/mo",
            enterprise: "Custom",
          },
          {
            feature: "Platform Audit Logs",
            free: "Not included",
            pro: "Not included",
            team: "Included",
            enterprise: "Included",
          },
          {
            feature: "Metrics endpoint",
            free: "Not included",
            pro: "Included",
            team: "Included",
            enterprise: "Included",
          },
          { feature: "SOC2", free: "Not included", pro: "Not included", team: "Included", enterprise: "Included" },
          { feature: "ISO 27001", free: "Not included", pro: "Not included", team: "Included", enterprise: "Included" },
          {
            feature: "HIPAA",
            free: "Not included",
            pro: "Not included",
            team: "Paid add-on",
            enterprise: "Paid add-on",
          },
          {
            feature: "AWS PrivateLink",
            free: "Not included",
            pro: "Not included",
            team: "Included",
            enterprise: "Included",
          },
          { feature: "SSO", free: "Not included", pro: "Not included", team: "Contact Us", enterprise: "Contact Us" },
          {
            feature: "Uptime SLAs",
            free: "Not included",
            pro: "Not included",
            team: "Not included",
            enterprise: "Included",
          },
          {
            feature: "Access Roles",
            free: "Owner, Admin, Dev",
            pro: "Owner, Admin, Dev",
            team: "Owner, Admin, Dev, Read-only",
            enterprise: "Custom scoped",
          },
          { feature: "Vanity URLs", free: "Not included", pro: "Included", team: "Included", enterprise: "Included" },
          {
            feature: "Custom Domains",
            free: "Not included",
            pro: "$10/domain/mo",
            team: "$10/domain/mo",
            enterprise: "1 + $10/domain/mo",
          },
        ],
      },
      {
        title: t("support"),
        rows: [
          { feature: "Community Support", free: "Included", pro: "Included", team: "Included", enterprise: "Included" },
          { feature: "Email Support", free: "Not included", pro: "Included", team: "Included", enterprise: "Included" },
          {
            feature: "Email Support SLA",
            free: "Not included",
            pro: "Not included",
            team: "Included",
            enterprise: "Included",
          },
          {
            feature: "Designated support",
            free: "Not included",
            pro: "Not included",
            team: "Not included",
            enterprise: "Included",
          },
          {
            feature: "On Boarding Support",
            free: "Not included",
            pro: "Not included",
            team: "Not included",
            enterprise: "Included",
          },
          {
            feature: "Designated Customer Success",
            free: "Not included",
            pro: "Not included",
            team: "Not included",
            enterprise: "Included",
          },
          {
            feature: "Security Questionnaire Help",
            free: "Not included",
            pro: "Not included",
            team: "Included",
            enterprise: "Included",
          },
        ],
      },
    ],
    faqTitle: t("faq.title"),
    faq: [
      { question: t("faq.q1"), answer: t("faq.a1") },
      { question: t("faq.q2"), answer: t("faq.a2") },
      { question: t("faq.q3"), answer: t("faq.a3") },
      { question: t("faq.q4"), answer: t("faq.a4") },
      { question: t("faq.q5"), answer: t("faq.a5") },
      { question: t("faq.q6"), answer: t("faq.a6") },
      { question: t("faq.q7"), answer: t("faq.a7") },
      { question: t("faq.q8"), answer: t("faq.a8") },
      { question: t("faq.q9"), answer: t("faq.a9") },
      { question: t("faq.q10"), answer: t("faq.a10") },
    ],
  };

  return <PricingPage t={translations} />;
}
